openapi: "3.0.1"
info:
  title: "Battlesnake Snake API"
  version: "2020.01"
  description: "Battlesnake participants implement this webhook API to power their snake. See play.battlesnake.com for details."
paths:
  /start:
    post:
      summary: "Signal start of a new game"
      tags:
        - endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SnakeRequest"
      responses:
        "200":
          description: "Snake configuration"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StartResponse"
  /move:
    post:
      summary: "Take a turn within a game"
      tags:
        - endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SnakeRequest"
      responses:
        "200":
          description: "Snake move"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MoveResponse"
  /end:
    post:
      summary: "Signal end of a game"
      tags:
        - endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SnakeRequest"
      responses:
        default:
          description: "Response ignored"
  /ping:
    post:
      summary: "A heartbeat call to check if your snake server is running"
      tags:
        - endpoints
      responses:
        "200":
          description: "Response code is required, but body is ignored"
components:
  schemas:
    Coords:
      type: object
      properties:
        x:
          type: integer
          minimum: 0
          example: 1
        y:
          type: integer
          minimum: 0
          example: 3
    Snake:
      type: object
      properties:
        id:
          type: string
          example: "snake-id-string"
        name:
          type: string
          example: "Sneky Snek"
        health:
          type: integer
          minimum: 0
          example: 90
        body:
          type: array
          items:
            $ref: "#/components/schemas/Coords"
        shout:
          type: string
          example: "Hello my name is Sneky Snek"
    Board:
      type: object
      properties:
        height:
          type: integer
          minimum: 1
          example: 15
        width:
          type: integer
          minimum: 1
          example: 15
        food:
          type: array
          items:
            $ref: "#/components/schemas/Coords"
        snakes:
          description: A list of snakes that are still alive
          type: array
          items:
            $ref: "#/components/schemas/Snake"
    Game:
      type: object
      properties:
        id:
          type: string
          example: "game-id-string"
    SnakeRequest:
      type: object
      properties:
        game:
          $ref: "#/components/schemas/Game"
        turn:
          type: integer
          minimum: 0
          example: 4
        board:
          $ref: "#/components/schemas/Board"
        you:
          $ref: "#/components/schemas/Snake"
    StartResponse:
      type: object
      properties:
        color:
          type: string
          example: "#ff00ff"
        headType:
          type: string
          enum: ["beluga", "bendr", "dead", "evil", "fang", "pixel", "regular", "safe", "sand-worm", "shades", "silly", "smile", "tongue"]
          example: "bendr"
        tailType:
          type: string
          enum: ["block-bum", "bolt", "curled", "fat-rattle", "freckled", "hook", "pixel", "regular", "round-bum", "sharp", "skinny", "small-rattle"]
          example: "pixel"
    MoveResponse:
      type: object
      required:
        - move
      properties:
        move:
          type: string
          enum: ["up", "down", "left", "right"]
          example: "right"
        shout:
          type: string
          maxLength: 256
          required: false
          example: "I am moving left!"
